/**
 * `@mcpjam/sdk/platform` — fetch-based client and curated operation catalog
 * for the MCPJam Platform API (`/api/v1`).
 *
 * Runtime-agnostic by construction: native fetch only, no Node built-ins, no
 * ambient environment reads (enforced by the repo-root
 * `check:platform-runtime-safety` guard). Consumed by the MCP worker
 * (Cloudflare), the CLI, and SDK users.
 */
export {
  PLATFORM_V1_ERROR_CODES,
  PlatformApiError,
  isPlatformApiError,
  type PlatformApiErrorCode,
  type PlatformApiErrorOptions,
  type PlatformV1ErrorCode,
} from "./errors.js";

export {
  DEFAULT_PLATFORM_API_BASE_URL,
  PlatformApiClient,
  type PlatformApiClientOptions,
} from "./client.js";

export type {
  PlatformChatbox,
  PlatformChatboxDetail,
  PlatformChatboxLink,
  PlatformChatboxServer,
  PlatformChatSession,
  PlatformComputerAttached,
  PlatformComputerReset,
  PlatformDoctorReport,
  PlatformImage,
  PlatformImageBuild,
  PlatformImageBuildStarted,
  PlatformImageBlueprintValidation,
  PlatformImageDeleted,
  PlatformEvalCase,
  PlatformEvalCaseDeleted,
  PlatformEvalCaseModel,
  PlatformEvalCasesGenerated,
  PlatformEvalStep,
  PlatformEvalIteration,
  PlatformEvalRun,
  PlatformEvalRunCreated,
  PlatformEvalRunEnvironment,
  PlatformEvalRunSummary,
  PlatformEvalSuite,
  PlatformEvalSuiteCreated,
  PlatformEvalSuiteDeleted,
  PlatformEvalSuiteDetail,
  PlatformEvalSuiteHost,
  PlatformEvalSuiteSchedule,
  PlatformEvalSuiteSettings,
  PlatformEnvironment,
  PlatformJourney,
  PlatformJourneyRun,
  PlatformJourneyRunAttempt,
  PlatformJourneyRunSession,
  PlatformJourneyRunTarget,
  PlatformJourneyRunCanceled,
  PlatformScenario,
  PlatformScenarioDeleted,
  PlatformEnvironmentCreateBody,
  PlatformEnvironmentCapabilities,
  PlatformEnvironmentResolved,
  PlatformEnvironmentRevisionBody,
  PlatformEnvironmentSkillSelection,
  PlatformEnvironmentUpdateBody,
  PlatformExpectedToolCall,
  PlatformHost,
  PlatformHostDeleted,
  PlatformHostDetail,
  PlatformMe,
  PlatformModel,
  PlatformOrganization,
  PlatformPage,
  PlatformPlugin,
  PlatformPluginComponentCounts,
  PlatformPluginServerComponent,
  PlatformPluginSkillComponent,
  PlatformPluginVersion,
  PlatformProject,
  PlatformProjectServer,
  PlatformServerConnection,
  PlatformServerConnectionCandidate,
  PlatformServerConnectionCreateBody,
  PlatformServerConnectionError,
  PlatformTunnelClosed,
  PlatformTunnelGrant,
  PublicCheck,
  PublicCheckOverride,
  PublicMatchOptions,
} from "./types.js";

export {
  SHOW_SERVERS_DOCTOR_CONCURRENCY,
  buildShowServersPayload,
  projectResolutionError,
  resolveProject,
  type BuildShowServersPayloadInput,
  type ProjectInfo,
  type ProjectResolution,
  type SelectedProjectInfo,
  type ServerEntry,
  type ServerInfo,
  type ServerPrimitiveCollection,
  type ServerPrimitiveListStatus,
  type ServerPrimitives,
  type ServerPromptArgumentInfo,
  type ServerPromptInfo,
  type ServerResourceInfo,
  type ServerStatus,
  type ServerToolInfo,
  type ServerTransportType,
  type ShowServersDoctorFn,
  type ShowServersPayload,
  type ShowServersSummary,
} from "./show-servers.js";

export {
  buildImageOperation,
  callServerToolOperation,
  closeTunnelOperation,
  createProjectOperation,
  createProjectServerOperation,
  createImageOperation,
  createEvalCaseOperation,
  createEvalSuiteOperation,
  createHostOperation,
  createTunnelOperation,
  cancelEvalRunOperation,
  deleteImageOperation,
  deleteEvalCaseOperation,
  deleteEvalSuiteOperation,
  deleteHostOperation,
  duplicateHostOperation,
  diagnoseServerOperation,
  exportServerOperation,
  getImageOperation,
  getMeOperation,
  listModelsOperation,
  listOrganizationsOperation,
  getProjectServerOperation,
  listImagesOperation,
  listImageBuildsOperation,
  promoteImageOperation,
  resetComputerOperation,
  updateImageOperation,
  useImageOperation,
  validateImageBlueprintOperation,
  generateEvalCasesOperation,
  getChatboxOperation,
  getEvalCaseOperation,
  getHostOperation,
  getEvalIterationTraceOperation,
  getEvalRunOperation,
  getEvalRunStepsOperation,
  getEvalSuiteOperation,
  getServerPromptOperation,
  listChatboxesOperation,
  listChatSessionsOperation,
  listEvalCasesOperation,
  listEvalRunIterationsOperation,
  listEvalSuiteRunsOperation,
  listEvalSuitesOperation,
  checkHostCompatibilityOperation,
  listHostsOperation,
  listEnvironmentsOperation,
  getEnvironmentCapabilitiesOperation,
  listJourneysOperation,
  listJourneyRunsOperation,
  getJourneyRunOperation,
  listJourneyRunSessionsOperation,
  launchJourneyRunOperation,
  cancelJourneyRunOperation,
  publishScenarioOperation,
  unpublishScenarioOperation,
  getEnvironmentOperation,
  resolveEnvironmentOperation,
  createEnvironmentOperation,
  updateEnvironmentOperation,
  archiveEnvironmentOperation,
  restoreEnvironmentOperation,
  listProjectPluginsOperation,
  getPluginVersionOperation,
  listProjectsOperation,
  listProjectServersOperation,
  listServerPromptsOperation,
  listServerResourcesOperation,
  listServerToolsOperation,
  readServerResourceOperation,
  runEvalCaseOperation,
  runEvalSuiteOperation,
  setEvalSuiteEnvironmentsOperation,
  setEvalSuiteScheduleOperation,
  showServersOperation,
  connectProjectServerOperation,
  getProjectServerConnectionStatusOperation,
  updateEvalCaseOperation,
  updateEvalSuiteOperation,
  updateHostOperation,
  setHostServersOperation,
  updateProjectServerOperation,
  updateProjectOperation,
  deleteProjectServerOperation,
  deleteProjectOperation,
  validateServerOperation,
  ALL_OPERATIONS,
  type CallServerToolInput,
  type CallServerToolResult,
  type CheckHostCompatibilityResult,
  type HostCompatibilityVerdict,
  type CloseTunnelInput,
  type CloseTunnelResult,
  type CreateEvalCaseInput,
  type CreateEvalSuiteInput,
  type CreateEvalSuiteResult,
  type CreateProjectInput,
  type CreateTunnelInput,
  type CreateTunnelResult,
  type DeleteEvalCaseInput,
  type DeleteEvalSuiteInput,
  type DeleteProjectInput,
  type DiagnoseServerResult,
  type DuplicateHostInput,
  type EvalRunScopedInput,
  type GenerateEvalCasesInput,
  type GetEvalCaseInput,
  type GetEvalSuiteInput,
  type ListEvalCasesInput,
  type SetEvalSuiteEnvironmentsInput,
  type SetEvalSuiteScheduleInput,
  type UpdateEvalCaseInput,
  type UpdateEvalSuiteInput,
  type UpdateProjectInput,
  type SetHostServersInput,
  type CreateHostInput,
  type DeleteHostInput,
  type GetHostInput,
  type ListHostsResult,
  type UpdateHostInput,
  type ListEnvironmentsInput,
  type ListEnvironmentsResult,
  type EnvironmentCapabilitiesInput,
  type EnvironmentCapabilitiesResult,
  type ListProjectPluginsInput,
  type ListProjectPluginsResult,
  type GetPluginVersionInput,
  // Journeys (Swarms) and scenarios (user testing). The operations above are
  // useless from outside without these — a caller cannot type the value an
  // operation returns, and reaching into `operations.js` for it would depend on
  // a path this barrel exists to hide.
  type ListJourneysInput,
  type ListJourneysResult,
  type ListJourneyRunsInput,
  type ListJourneyRunsResult,
  type GetJourneyRunInput,
  type GetJourneyRunResult,
  type ListJourneyRunSessionsInput,
  type ListJourneyRunSessionsResult,
  type LaunchJourneyRunInput,
  type LaunchJourneyRunResult,
  type CancelJourneyRunInput,
  type CancelJourneyRunResult,
  type PublishScenarioInput,
  type PublishScenarioResult,
  type UnpublishScenarioInput,
  type UnpublishScenarioResult,
  type EnvironmentSelectorInput,
  type EnvironmentRevisionInput,
  type CreateEnvironmentInput,
  type UpdateEnvironmentInput,
  type CreateImageInput,
  type ImageSelectorInput,
  type ListImagesResult,
  type ListImageBuildsResult,
  type UpdateImageInput,
  type ValidateImageBlueprintInput,
  type GetChatboxInput,
  type GetChatboxResult,
  type GetEvalIterationTraceInput,
  type GetEvalIterationTraceResult,
  type CancelEvalRunResult,
  type GetEvalRunStepsInput,
  type GetEvalRunStepsResult,
  type GetEvalRunResult,
  type GetServerPromptInput,
  type GetServerPromptResult,
  type ListChatboxesResult,
  type ListChatSessionsInput,
  type ListChatSessionsResult,
  type ListEvalRunIterationsInput,
  type ListEvalRunIterationsResult,
  type ListEvalSuiteRunsInput,
  type ListEvalSuiteRunsResult,
  type ListEvalSuitesResult,
  type ListProjectServersResult,
  type ListProjectsInput,
  type PlatformOperation,
  type PlatformOperationContext,
  type AnyPlatformOperation,
  type CreateProjectServerInput,
  type GetProjectServerInput,
  type UpdateProjectServerInput,
  type ProjectScopedInput,
  type ConnectProjectServerInput,
  type GetProjectServerConnectionStatusInput,
  type ReadServerResourceInput,
  type ReadServerResourceResult,
  type ResolvedServerInfo,
  type RunEvalCaseInput,
  type RunEvalCaseResult,
  type RunEvalSuiteInput,
  type RunEvalSuiteResult,
  type ServerPagedInput,
  type ServerPagedResult,
  type ServerScopedInput,
} from "./operations.js";

export {
  collectStepScreenshots,
  selectStepScreenshots,
  type CollectScreenshotsOptions,
  type StepScreenshot,
} from "./step-evidence.js";
